win = am.window
{
    -- mode = "fullscreen",  --"windowed",
    width = 360,    --576,    --1258,   --640,    --160,
    height = 360,   --1178,  --360,   --100,
    -- physical_size = vec2(1920,1200),
    title = "Sum,mon",
    -- resizable = false,
    -- borderless = false,    --false,
    -- borderless = true,    --false,
    -- highdpi = false,
    -- depth_buffer = false,
    -- stencil_buffer = false,
    -- stencil_clear_value = 0,
    -- lock_pointer = false,
    -- show_cursor = false,
    clear_color = vec4(0.5,0.5,0.5,1),
    -- clear_color = vec4(0.3,0.5,0.5,1),
    -- letterbox = false,
    -- msaa_samples = 0,   --4,
    --projection = mat4(),
}
